name: 压缩发布

on:
  schedule:
    - cron: '0 3,20 * * *'
  workflow_dispatch:
env:
  TZ: Asia/Shanghai

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      ver: ${{ steps.getversion.outputs.ver }}
      cver: ${{ steps.getversion.outputs.cver }}
    steps:
      -
        name: 检查更新
        id: getversion
        run: |
          ver=`curl https://api.github.com/repos/fatedier/frp/releases/latest | jq -r '.tag_name' | tr -d " v "`
          cver=`curl https://api.github.com/repos/lmq8267/frp/releases/latest | jq -r '.tag_name'`
          echo "ver=${ver}" >> $GITHUB_OUTPUT
          echo "cver=${cver}" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    needs: check
    if: ${{ needs.check.outputs.ver != needs.check.outputs.cver }}
    steps:
      -
        name: 检查代码仓库
        uses: actions/checkout@v3
      - name: 安装 UPX
        uses: crazy-max/ghaction-upx@v3
        with:
          version: latest
          install-only: true
      - 
        name: 下载并压缩
        run: |
          rm -rf /opt/st
          git clone https://github.com/lmq8267/cloudflared.git /opt/st
          tag=`curl https://api.github.com/repos/fatedier/frp/releases/latest | grep 'tag_name' | cut -d\" -f4 | tr -d " v "`
          echo tag=$tag
          sudo chmod 0777 /etc/resolv.conf
          cat >>/etc/resolv.conf <<EOF
          nameserver 8.8.8.8 
          nameserver 4.4.4.4
          EOF
          curl -k -L -o "/opt/st/frp-linux-mipsle.tar.gz" "https://github.com/fatedier/frp/releases/download/v${tag}/frp_${tag}_linux_mipsle.tar.gz" 
          tar -xzvf /opt/st/frp-linux-mipsle.tar.gz -C /opt
          tar -xvf /opt/st/upx-3.95-amd64_linux.tar.xz -C /opt
          chmod 777 /opt/st/strip
          cd /opt/frp_${tag}_linux_mipsle
          /opt/st/strip frpc
          /opt/st/strip frps
          upx --lzma --best frpc
          upx --lzma --best frps
          cd /opt
          tar czvf frp_${tag}_linux_mipsle.tar.gz frp_${tag}_linux_mipsle
          echo $(md5sum frp_${tag}_linux_mipsle.tar.gz | awk '{print $1;}') >MD5.txt
          echo "build_time=$(date '+%Y年%m月%d日%H:%M:%S' | jq -sRr @uri)" >> $GITHUB_ENV
          echo "tag=${tag}" >> $GITHUB_ENV
      - 
        name: 发布
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.c8 }}
          body: |
           > ### ![](https://img.shields.io/badge/%E7%BC%96%E8%AF%91%E6%97%B6%E9%97%B4-${{ env.build_time }}-8267?logo=github&labelColor=%E9%A1%BB)![](https://img.shields.io/github/downloads/lmq8267/frp/${{ needs.check.outputs.ver }}/total?label=%E4%B8%8B%E8%BD%BD%E6%AC%A1%E6%95%B0&logo=github)

           **[官方更新说明](https://github.com/fatedier/frp/releases)**
          tag_name: ${{ needs.check.outputs.ver }}
          files: |
              /opt/frp_${{ env.tag }}_linux_mipsle.tar.gz
              /opt/frp_${{ env.tag }}_linux_mipsle/frpc
              /opt/frp_${{ env.tag }}_linux_mipsle/frps
              /opt/MD5.txt
      - 
       name: 删除工作流
       uses: GitRML/delete-workflow-runs@main
       with:
        token: ${{ secrets.c8 }}
        retain_days: 2
        keep_minimum_runs: 0
  keepalive-workflow:
    # github超过60天未提交将自动停止工作流
    name: 工作流保活 
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v2
        #with:
          #use_api: true
